main: me.noodles.staff.Main
name: StaffMode
version: 6.0
author: BGHDNetwork
Website: https://www.spigotmc.org/resources/staffmode/40929

commands:   
   staffmode:
      description: StaffMode
      aliases: [sg, staffgui]
